### ISSUE TITLE
Cannot get play URL  for...

### ISSUE THREAD

**Issue by jrwendt** [danielvijge/lms_mixcloud#10] opened 2019-11-26 03:23 UTC
Hi Daniel,
One of the problems with putting your talents into writing a Squeezebox pluggin is you are continuously bothered by users with their issues. 
Sorry to add to this list…
But I am having some issues with my Mixcloud plugin. It looks like Mixcloud added some kind of “feature” that baffles your 0.1.7 version from http://danielvijge.github.io/lms_mixcloud/public.xml

[19-11-25 20:37:15.5525] Plugins::MixCloud::ProtocolHandler::getTrackUrl (109) Error: Cannot get play URL for djkennyperez/irf-search-for-the-best-uscanada-college-radio-jockey-2015/ from http://www.mixcloud-downloader.com/djkennyperez/irf-search-for-the-best-uscanada-college-radio-jockey-2015/

Have any ideas?

Thanks for the work you are doing to support the Squeezebox system

--John

**Comment by timatinsipid** [comment] 2021-10-03 20:29
Am also having issues with streams in the plugin

[21-10-03 13:19:13.2012] Plugins::MixCloud::ProtocolHandler::__ANON__ (200) Error getting play URL for mixcloud://strictlykev/strictlys-new-year-homework-pt2-10011999/ => 404 Not Found
[21-10-03 13:19:13.2017] Slim::Player::Song::open (417) Error: Couldn't create command line for unk playback for [mixcloud://strictlykev/strictlys-new-year-homework-pt2-10011999/]
[21-10-03 13:19:19.7763] Plugins::MixCloud::ProtocolHandler::__ANON__ (200) Error getting play URL for mixcloud://strictlykev/dj-food-dk-now-listen-directors-cut-pt2-170901/ => 404 Not Found
[21-10-03 13:19:19.7768] Slim::Player::Song::open (417) Error: Couldn't create command line for unk playback for [mixcloud://strictlykev/dj-food-dk-now-listen-directors-cut-pt2-170901/]
[21-10-03 13:19:30.9151] Plugins::MixCloud::ProtocolHandler::__ANON__ (200) Error getting play URL for mixcloud://strictlykev/dj-food-dk-now-listen-directors-cut-pt1-170901/ => 404 Not Found
[21-10-03 13:19:30.9156] Slim::Player::Song::open (417) Error: Couldn't create command line for unk playback for [mixcloud://strictlykev/dj-food-dk-now-listen-directors-cut-pt1-170901/]
[21-10-03 13:19:38.7902] Plugins::MixCloud::ProtocolHandler::__ANON__ (200) Error getting play URL for mixcloud://strictlykev/openmind-collective-solid-steel-debut-11071993/ => 404 Not Found
[21-10-03 13:19:38.7907] Slim::Player::Song::open (417) Error: Couldn't create command line for unk playback for [mixcloud://strictlykev/openmind-collective-solid-steel-debut-11071993/]
[21-10-03 13:19:58.0829] Plugins::MixCloud::ProtocolHandler::__ANON__ (200) Error getting play URL for mixcloud://strictlykev/lynch-party-mix-2/ => 404 Not Found
[21-10-03 13:19:58.0834] Slim::Player::Song::open (417) Error: Couldn't create command line for unk playback for [mixcloud://strictlykev/lynch-party-mix-2/]

This does not work
https://www.mixcloud.com/strictlykev/strictlys-new-year-homework-pt2-10011999/
this file works
https://www.mixcloud.com/strictlykev/coldcut-solid-sphinx-new-year-92-93/

**Comment by danielvijge** [comment] 2021-10-04 15:21
Mixcloud doesn't have a public API to stream tracks outside of their website/app. The plugin uses dlmixcloud.com to get the actual file to stream. This does not take into account the user login. For the mentioned track it just returns a 404 Not Found error. I guess this is because the track is marked is _exclusive_. I also cannot play it via Mixcloud's website.
Nothing that can be done about it as long as MixCloud doesn't have an open API to stream tracks.

**Comment by kwarklabs** [comment] 2022-04-11 15:27
Confirmed that track is not playing because it is marked "exclusive" and that the Mixcloud API does not provide a way to make this work at this time. Suggest closing this issue.

**Closed** 2022-04-19 20:00 UTC
